name: Test

on:
  push:
    branches: [main]
    paths:
      - "**/*.swift"
  pull_request:
    paths:
      - "**/*.swift"

jobs:
  test:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v4

      - name: Install tools
        run: brew install xcbeautify

      - name: Run tests
        run: bash scripts/test.sh
